sudo: required
dist: trusty
os: linux
language: node_js
node_js:
- '8'
addons:
  chrome: stable
cache: 
directories:
- node_modules
before_install:
   google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

script:
- npm update -g npm
- npm run doc
- cp dist/ngx-callisto/index.html dist/ngx-callisto/404.html

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/ngx-callisto
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  repo: clabroche/ngx-callisto.github.io
  target_branch: master